services:
  app:
    build: ./app
    networks:
      - app-network
    ports:
      - "8000:8000"
  data_extractor:
    build: ./data_extractor
    networks:
      - app-network
    ports:
      - "5000:5000"
  summarizer:
    build: ./summarizer
    networks:
      - app-network
    ports:
      - "4040:4040"
  database_handler:
    build: ./database_handler
    networks:
      - app-network
    volumes:
      - type: volume
        source: volume-db
        target: /etc/volume
    environment:
      - DATABASE_URL=sqlite:////etc/volume/project.db
    ports:
      - "4444:4444"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network
volumes:
  volume-db:
networks:
  app-network:
    driver: bridge