services:
  target_db:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: target_user
      POSTGRES_PASSWORD: target_password
      POSTGRES_DB: target_db
    networks:
      - elt_network
  elt_script:
    build: ./elt
    command: ["python", "elt_script.py"]
    environment:
      - DATABASE_URL=sqlite:////data/volume/project.db
    depends_on:
      - source_db
      - target_db
    networks:
      - elt_network
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.16
    command:
      ["run",
      "--profiles-dir",
      "/root",
      "--project-dir",
      "/dbt"
      ]
    networks:
      - elt_network
    volumes:
      - ./custom_postgres:/dbt
      - ~/.dbt:/root
    depends_on:
      - elt_script
    environment:
      DBT_PROFILE: default
      DBT_TARGET: dev

networks:
  elt_network:
    driver: bridge

volumes:
  linkedin_helper_volume-db:
    external: true
